<?php

/**
 * @file
 * Flush primary module file
 *
 * Implements hook_perm, hook_menu, hook_init
 * and a function to handle the result for Flush.
 */

/**
 * Implements hook_permission().
 */
function flush_permission() {
  return array(
    'access flush' => array(
      'title' => t('Access Flush'),
      'description' => t('Access the Flush window to clear Drupal Cache'),
    ),
  );
}

/**
* Implementation of hook_menu()
*/
function flush_menu() {

	$items['admin/flush/run'] = array(
		'title' => 'Flush Cache',
		'page callback' => 'flush_clear_cache',
		'access arguments' => array('administer users'),
		'type' => MENU_CALLBACK,
	);
	
	return $items;
}

function flush_clear_cache(){
	
	drupal_set_message(t('The Flush module just flushed the cache.'), 'status');
	
	drupal_flush_all_caches();
	
	$home = $_SERVER['HTTP_REFERER'];
	
	header("Location: $home");
	exit;
	
}


/**
 * Implements hook_init().
 * 
 */
function flush_init() {
  // Only users with the permission access Flush can use Flush.
  if (user_access('access flush')) {
    // Add the javascript file.
    drupal_add_js(drupal_get_path('module', 'flush') . '/js/flush.js', array('type' => 'file'));
  }

}

/**
 * Implements hook_hook_info().
 */
function flush_hook_info() {
  $hooks = array(
    'flush_command' => array(
      'group' => 'flush',
    ),
  );

  return $hooks;
}